/**
 * Generated by `supabase gen types typescript --linked > lib/supabase/types.ts`
 * Placeholder until migration is applied. Run the gen command after Day 1.
 */
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
